// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdb

import (
	"context"

	"github.com/alwitt/cairn/db"
	"github.com/alwitt/cairn/models"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// DefineNewArtifact provides a mock function for the type Database
func (_mock *Database) DefineNewArtifact(ctx context.Context, params db.NewArtifactParameter) (models.Artifact, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewArtifactParameter) (models.Artifact, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewArtifactParameter) models.Artifact); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.NewArtifactParameter) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewArtifact'
type Database_DefineNewArtifact_Call struct {
	*mock.Call
}

// DefineNewArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.NewArtifactParameter
func (_e *Database_Expecter) DefineNewArtifact(ctx interface{}, params interface{}) *Database_DefineNewArtifact_Call {
	return &Database_DefineNewArtifact_Call{Call: _e.mock.On("DefineNewArtifact", ctx, params)}
}

func (_c *Database_DefineNewArtifact_Call) Run(run func(ctx context.Context, params db.NewArtifactParameter)) *Database_DefineNewArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.NewArtifactParameter
		if args[1] != nil {
			arg1 = args[1].(db.NewArtifactParameter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DefineNewArtifact_Call) Return(artifact models.Artifact, err error) *Database_DefineNewArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Database_DefineNewArtifact_Call) RunAndReturn(run func(ctx context.Context, params db.NewArtifactParameter) (models.Artifact, error)) *Database_DefineNewArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// DefineNewWorkspace provides a mock function for the type Database
func (_mock *Database) DefineNewWorkspace(ctx context.Context, params db.NewWorkspaceParameter) (models.Workspace, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewWorkspace")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewWorkspaceParameter) (models.Workspace, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewWorkspaceParameter) models.Workspace); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.NewWorkspaceParameter) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewWorkspace'
type Database_DefineNewWorkspace_Call struct {
	*mock.Call
}

// DefineNewWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.NewWorkspaceParameter
func (_e *Database_Expecter) DefineNewWorkspace(ctx interface{}, params interface{}) *Database_DefineNewWorkspace_Call {
	return &Database_DefineNewWorkspace_Call{Call: _e.mock.On("DefineNewWorkspace", ctx, params)}
}

func (_c *Database_DefineNewWorkspace_Call) Run(run func(ctx context.Context, params db.NewWorkspaceParameter)) *Database_DefineNewWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.NewWorkspaceParameter
		if args[1] != nil {
			arg1 = args[1].(db.NewWorkspaceParameter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DefineNewWorkspace_Call) Return(workspace models.Workspace, err error) *Database_DefineNewWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Database_DefineNewWorkspace_Call) RunAndReturn(run func(ctx context.Context, params db.NewWorkspaceParameter) (models.Workspace, error)) *Database_DefineNewWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteArtifact provides a mock function for the type Database
func (_mock *Database) DeleteArtifact(ctx context.Context, artifactID string) error {
	ret := _mock.Called(ctx, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, artifactID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type Database_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
func (_e *Database_Expecter) DeleteArtifact(ctx interface{}, artifactID interface{}) *Database_DeleteArtifact_Call {
	return &Database_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", ctx, artifactID)}
}

func (_c *Database_DeleteArtifact_Call) Run(run func(ctx context.Context, artifactID string)) *Database_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteArtifact_Call) Return(err error) *Database_DeleteArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteArtifact_Call) RunAndReturn(run func(ctx context.Context, artifactID string) error) *Database_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function for the type Database
func (_mock *Database) DeleteWorkspace(ctx context.Context, workspaceID string) error {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type Database_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *Database_Expecter) DeleteWorkspace(ctx interface{}, workspaceID interface{}) *Database_DeleteWorkspace_Call {
	return &Database_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", ctx, workspaceID)}
}

func (_c *Database_DeleteWorkspace_Call) Run(run func(ctx context.Context, workspaceID string)) *Database_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteWorkspace_Call) Return(err error) *Database_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) error) *Database_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifact provides a mock function for the type Database
func (_mock *Database) GetArtifact(ctx context.Context, artifactID string) (models.Artifact, error) {
	ret := _mock.Called(ctx, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Artifact, error)); ok {
		return returnFunc(ctx, artifactID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Artifact); ok {
		r0 = returnFunc(ctx, artifactID)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, artifactID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifact'
type Database_GetArtifact_Call struct {
	*mock.Call
}

// GetArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
func (_e *Database_Expecter) GetArtifact(ctx interface{}, artifactID interface{}) *Database_GetArtifact_Call {
	return &Database_GetArtifact_Call{Call: _e.mock.On("GetArtifact", ctx, artifactID)}
}

func (_c *Database_GetArtifact_Call) Run(run func(ctx context.Context, artifactID string)) *Database_GetArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetArtifact_Call) Return(artifact models.Artifact, err error) *Database_GetArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Database_GetArtifact_Call) RunAndReturn(run func(ctx context.Context, artifactID string) (models.Artifact, error)) *Database_GetArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactByName provides a mock function for the type Database
func (_mock *Database) GetArtifactByName(ctx context.Context, workspaceID string, name string) (models.Artifact, error) {
	ret := _mock.Called(ctx, workspaceID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactByName")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (models.Artifact, error)); ok {
		return returnFunc(ctx, workspaceID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) models.Artifact); ok {
		r0 = returnFunc(ctx, workspaceID, name)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workspaceID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetArtifactByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactByName'
type Database_GetArtifactByName_Call struct {
	*mock.Call
}

// GetArtifactByName is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - name string
func (_e *Database_Expecter) GetArtifactByName(ctx interface{}, workspaceID interface{}, name interface{}) *Database_GetArtifactByName_Call {
	return &Database_GetArtifactByName_Call{Call: _e.mock.On("GetArtifactByName", ctx, workspaceID, name)}
}

func (_c *Database_GetArtifactByName_Call) Run(run func(ctx context.Context, workspaceID string, name string)) *Database_GetArtifactByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_GetArtifactByName_Call) Return(artifact models.Artifact, err error) *Database_GetArtifactByName_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Database_GetArtifactByName_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, name string) (models.Artifact, error)) *Database_GetArtifactByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type Database
func (_mock *Database) GetWorkspace(ctx context.Context, workspaceID string) (models.Workspace, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Workspace, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Workspace); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type Database_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *Database_Expecter) GetWorkspace(ctx interface{}, workspaceID interface{}) *Database_GetWorkspace_Call {
	return &Database_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", ctx, workspaceID)}
}

func (_c *Database_GetWorkspace_Call) Run(run func(ctx context.Context, workspaceID string)) *Database_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetWorkspace_Call) Return(workspace models.Workspace, err error) *Database_GetWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Database_GetWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) (models.Workspace, error)) *Database_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspaceByName provides a mock function for the type Database
func (_mock *Database) GetWorkspaceByName(ctx context.Context, name string) (models.Workspace, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceByName")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Workspace, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Workspace); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetWorkspaceByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspaceByName'
type Database_GetWorkspaceByName_Call struct {
	*mock.Call
}

// GetWorkspaceByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Database_Expecter) GetWorkspaceByName(ctx interface{}, name interface{}) *Database_GetWorkspaceByName_Call {
	return &Database_GetWorkspaceByName_Call{Call: _e.mock.On("GetWorkspaceByName", ctx, name)}
}

func (_c *Database_GetWorkspaceByName_Call) Run(run func(ctx context.Context, name string)) *Database_GetWorkspaceByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetWorkspaceByName_Call) Return(workspace models.Workspace, err error) *Database_GetWorkspaceByName_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Database_GetWorkspaceByName_Call) RunAndReturn(run func(ctx context.Context, name string) (models.Workspace, error)) *Database_GetWorkspaceByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListArtifacts provides a mock function for the type Database
func (_mock *Database) ListArtifacts(ctx context.Context, filters db.ArtifactQueryFilter) ([]models.Artifact, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListArtifacts")
	}

	var r0 []models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ArtifactQueryFilter) ([]models.Artifact, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ArtifactQueryFilter) []models.Artifact); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ArtifactQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListArtifacts'
type Database_ListArtifacts_Call struct {
	*mock.Call
}

// ListArtifacts is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.ArtifactQueryFilter
func (_e *Database_Expecter) ListArtifacts(ctx interface{}, filters interface{}) *Database_ListArtifacts_Call {
	return &Database_ListArtifacts_Call{Call: _e.mock.On("ListArtifacts", ctx, filters)}
}

func (_c *Database_ListArtifacts_Call) Run(run func(ctx context.Context, filters db.ArtifactQueryFilter)) *Database_ListArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ArtifactQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.ArtifactQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListArtifacts_Call) Return(artifacts []models.Artifact, err error) *Database_ListArtifacts_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *Database_ListArtifacts_Call) RunAndReturn(run func(ctx context.Context, filters db.ArtifactQueryFilter) ([]models.Artifact, error)) *Database_ListArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// ListSystemEvents provides a mock function for the type Database
func (_mock *Database) ListSystemEvents(ctx context.Context, filters db.SystemEventQueryFilter) ([]models.SystemEventAudit, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListSystemEvents")
	}

	var r0 []models.SystemEventAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SystemEventQueryFilter) ([]models.SystemEventAudit, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SystemEventQueryFilter) []models.SystemEventAudit); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SystemEventAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.SystemEventQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListSystemEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSystemEvents'
type Database_ListSystemEvents_Call struct {
	*mock.Call
}

// ListSystemEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.SystemEventQueryFilter
func (_e *Database_Expecter) ListSystemEvents(ctx interface{}, filters interface{}) *Database_ListSystemEvents_Call {
	return &Database_ListSystemEvents_Call{Call: _e.mock.On("ListSystemEvents", ctx, filters)}
}

func (_c *Database_ListSystemEvents_Call) Run(run func(ctx context.Context, filters db.SystemEventQueryFilter)) *Database_ListSystemEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.SystemEventQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.SystemEventQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListSystemEvents_Call) Return(systemEventAudits []models.SystemEventAudit, err error) *Database_ListSystemEvents_Call {
	_c.Call.Return(systemEventAudits, err)
	return _c
}

func (_c *Database_ListSystemEvents_Call) RunAndReturn(run func(ctx context.Context, filters db.SystemEventQueryFilter) ([]models.SystemEventAudit, error)) *Database_ListSystemEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaceArtifacts provides a mock function for the type Database
func (_mock *Database) ListWorkspaceArtifacts(ctx context.Context, workspaceID string, filters db.ArtifactQueryFilter) ([]models.Artifact, error) {
	ret := _mock.Called(ctx, workspaceID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaceArtifacts")
	}

	var r0 []models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.ArtifactQueryFilter) ([]models.Artifact, error)); ok {
		return returnFunc(ctx, workspaceID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.ArtifactQueryFilter) []models.Artifact); ok {
		r0 = returnFunc(ctx, workspaceID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.ArtifactQueryFilter) error); ok {
		r1 = returnFunc(ctx, workspaceID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListWorkspaceArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaceArtifacts'
type Database_ListWorkspaceArtifacts_Call struct {
	*mock.Call
}

// ListWorkspaceArtifacts is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - filters db.ArtifactQueryFilter
func (_e *Database_Expecter) ListWorkspaceArtifacts(ctx interface{}, workspaceID interface{}, filters interface{}) *Database_ListWorkspaceArtifacts_Call {
	return &Database_ListWorkspaceArtifacts_Call{Call: _e.mock.On("ListWorkspaceArtifacts", ctx, workspaceID, filters)}
}

func (_c *Database_ListWorkspaceArtifacts_Call) Run(run func(ctx context.Context, workspaceID string, filters db.ArtifactQueryFilter)) *Database_ListWorkspaceArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.ArtifactQueryFilter
		if args[2] != nil {
			arg2 = args[2].(db.ArtifactQueryFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_ListWorkspaceArtifacts_Call) Return(artifacts []models.Artifact, err error) *Database_ListWorkspaceArtifacts_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *Database_ListWorkspaceArtifacts_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, filters db.ArtifactQueryFilter) ([]models.Artifact, error)) *Database_ListWorkspaceArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type Database
func (_mock *Database) ListWorkspaces(ctx context.Context, filters db.WorkspaceQueryFilter) ([]models.Workspace, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.WorkspaceQueryFilter) ([]models.Workspace, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.WorkspaceQueryFilter) []models.Workspace); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.WorkspaceQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type Database_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.WorkspaceQueryFilter
func (_e *Database_Expecter) ListWorkspaces(ctx interface{}, filters interface{}) *Database_ListWorkspaces_Call {
	return &Database_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", ctx, filters)}
}

func (_c *Database_ListWorkspaces_Call) Run(run func(ctx context.Context, filters db.WorkspaceQueryFilter)) *Database_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.WorkspaceQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.WorkspaceQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListWorkspaces_Call) Return(workspaces []models.Workspace, err error) *Database_ListWorkspaces_Call {
	_c.Call.Return(workspaces, err)
	return _c
}

func (_c *Database_ListWorkspaces_Call) RunAndReturn(run func(ctx context.Context, filters db.WorkspaceQueryFilter) ([]models.Workspace, error)) *Database_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// MarkArtifactMissingObject provides a mock function for the type Database
func (_mock *Database) MarkArtifactMissingObject(ctx context.Context, artifactID string) error {
	ret := _mock.Called(ctx, artifactID)

	if len(ret) == 0 {
		panic("no return value specified for MarkArtifactMissingObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, artifactID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkArtifactMissingObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkArtifactMissingObject'
type Database_MarkArtifactMissingObject_Call struct {
	*mock.Call
}

// MarkArtifactMissingObject is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
func (_e *Database_Expecter) MarkArtifactMissingObject(ctx interface{}, artifactID interface{}) *Database_MarkArtifactMissingObject_Call {
	return &Database_MarkArtifactMissingObject_Call{Call: _e.mock.On("MarkArtifactMissingObject", ctx, artifactID)}
}

func (_c *Database_MarkArtifactMissingObject_Call) Run(run func(ctx context.Context, artifactID string)) *Database_MarkArtifactMissingObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkArtifactMissingObject_Call) Return(err error) *Database_MarkArtifactMissingObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkArtifactMissingObject_Call) RunAndReturn(run func(ctx context.Context, artifactID string) error) *Database_MarkArtifactMissingObject_Call {
	_c.Call.Return(run)
	return _c
}

// MarkWorkspaceVolumeNone provides a mock function for the type Database
func (_mock *Database) MarkWorkspaceVolumeNone(ctx context.Context, workspaceID string) error {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkWorkspaceVolumeNone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkWorkspaceVolumeNone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkWorkspaceVolumeNone'
type Database_MarkWorkspaceVolumeNone_Call struct {
	*mock.Call
}

// MarkWorkspaceVolumeNone is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *Database_Expecter) MarkWorkspaceVolumeNone(ctx interface{}, workspaceID interface{}) *Database_MarkWorkspaceVolumeNone_Call {
	return &Database_MarkWorkspaceVolumeNone_Call{Call: _e.mock.On("MarkWorkspaceVolumeNone", ctx, workspaceID)}
}

func (_c *Database_MarkWorkspaceVolumeNone_Call) Run(run func(ctx context.Context, workspaceID string)) *Database_MarkWorkspaceVolumeNone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkWorkspaceVolumeNone_Call) Return(err error) *Database_MarkWorkspaceVolumeNone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkWorkspaceVolumeNone_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) error) *Database_MarkWorkspaceVolumeNone_Call {
	_c.Call.Return(run)
	return _c
}

// MarkWorkspaceVolumeReady provides a mock function for the type Database
func (_mock *Database) MarkWorkspaceVolumeReady(ctx context.Context, workspaceID string) error {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkWorkspaceVolumeReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkWorkspaceVolumeReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkWorkspaceVolumeReady'
type Database_MarkWorkspaceVolumeReady_Call struct {
	*mock.Call
}

// MarkWorkspaceVolumeReady is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *Database_Expecter) MarkWorkspaceVolumeReady(ctx interface{}, workspaceID interface{}) *Database_MarkWorkspaceVolumeReady_Call {
	return &Database_MarkWorkspaceVolumeReady_Call{Call: _e.mock.On("MarkWorkspaceVolumeReady", ctx, workspaceID)}
}

func (_c *Database_MarkWorkspaceVolumeReady_Call) Run(run func(ctx context.Context, workspaceID string)) *Database_MarkWorkspaceVolumeReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkWorkspaceVolumeReady_Call) Return(err error) *Database_MarkWorkspaceVolumeReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkWorkspaceVolumeReady_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) error) *Database_MarkWorkspaceVolumeReady_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactDescription provides a mock function for the type Database
func (_mock *Database) UpdateArtifactDescription(ctx context.Context, artifactID string, newDescription *string) error {
	ret := _mock.Called(ctx, artifactID, newDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactDescription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = returnFunc(ctx, artifactID, newDescription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateArtifactDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactDescription'
type Database_UpdateArtifactDescription_Call struct {
	*mock.Call
}

// UpdateArtifactDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - newDescription *string
func (_e *Database_Expecter) UpdateArtifactDescription(ctx interface{}, artifactID interface{}, newDescription interface{}) *Database_UpdateArtifactDescription_Call {
	return &Database_UpdateArtifactDescription_Call{Call: _e.mock.On("UpdateArtifactDescription", ctx, artifactID, newDescription)}
}

func (_c *Database_UpdateArtifactDescription_Call) Run(run func(ctx context.Context, artifactID string, newDescription *string)) *Database_UpdateArtifactDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateArtifactDescription_Call) Return(err error) *Database_UpdateArtifactDescription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateArtifactDescription_Call) RunAndReturn(run func(ctx context.Context, artifactID string, newDescription *string) error) *Database_UpdateArtifactDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactName provides a mock function for the type Database
func (_mock *Database) UpdateArtifactName(ctx context.Context, artifactID string, newName string) error {
	ret := _mock.Called(ctx, artifactID, newName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, artifactID, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateArtifactName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactName'
type Database_UpdateArtifactName_Call struct {
	*mock.Call
}

// UpdateArtifactName is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - newName string
func (_e *Database_Expecter) UpdateArtifactName(ctx interface{}, artifactID interface{}, newName interface{}) *Database_UpdateArtifactName_Call {
	return &Database_UpdateArtifactName_Call{Call: _e.mock.On("UpdateArtifactName", ctx, artifactID, newName)}
}

func (_c *Database_UpdateArtifactName_Call) Run(run func(ctx context.Context, artifactID string, newName string)) *Database_UpdateArtifactName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateArtifactName_Call) Return(err error) *Database_UpdateArtifactName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateArtifactName_Call) RunAndReturn(run func(ctx context.Context, artifactID string, newName string) error) *Database_UpdateArtifactName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactObject provides a mock function for the type Database
func (_mock *Database) UpdateArtifactObject(ctx context.Context, artifactID string, objectKey string, mimeType string, size int64) error {
	ret := _mock.Called(ctx, artifactID, objectKey, mimeType, size)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64) error); ok {
		r0 = returnFunc(ctx, artifactID, objectKey, mimeType, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateArtifactObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactObject'
type Database_UpdateArtifactObject_Call struct {
	*mock.Call
}

// UpdateArtifactObject is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - objectKey string
//   - mimeType string
//   - size int64
func (_e *Database_Expecter) UpdateArtifactObject(ctx interface{}, artifactID interface{}, objectKey interface{}, mimeType interface{}, size interface{}) *Database_UpdateArtifactObject_Call {
	return &Database_UpdateArtifactObject_Call{Call: _e.mock.On("UpdateArtifactObject", ctx, artifactID, objectKey, mimeType, size)}
}

func (_c *Database_UpdateArtifactObject_Call) Run(run func(ctx context.Context, artifactID string, objectKey string, mimeType string, size int64)) *Database_UpdateArtifactObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Database_UpdateArtifactObject_Call) Return(err error) *Database_UpdateArtifactObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateArtifactObject_Call) RunAndReturn(run func(ctx context.Context, artifactID string, objectKey string, mimeType string, size int64) error) *Database_UpdateArtifactObject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceDescription provides a mock function for the type Database
func (_mock *Database) UpdateWorkspaceDescription(ctx context.Context, workspaceID string, newDescription *string) error {
	ret := _mock.Called(ctx, workspaceID, newDescription)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceDescription")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = returnFunc(ctx, workspaceID, newDescription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateWorkspaceDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceDescription'
type Database_UpdateWorkspaceDescription_Call struct {
	*mock.Call
}

// UpdateWorkspaceDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - newDescription *string
func (_e *Database_Expecter) UpdateWorkspaceDescription(ctx interface{}, workspaceID interface{}, newDescription interface{}) *Database_UpdateWorkspaceDescription_Call {
	return &Database_UpdateWorkspaceDescription_Call{Call: _e.mock.On("UpdateWorkspaceDescription", ctx, workspaceID, newDescription)}
}

func (_c *Database_UpdateWorkspaceDescription_Call) Run(run func(ctx context.Context, workspaceID string, newDescription *string)) *Database_UpdateWorkspaceDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateWorkspaceDescription_Call) Return(err error) *Database_UpdateWorkspaceDescription_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateWorkspaceDescription_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, newDescription *string) error) *Database_UpdateWorkspaceDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceName provides a mock function for the type Database
func (_mock *Database) UpdateWorkspaceName(ctx context.Context, workspaceID string, newName string) error {
	ret := _mock.Called(ctx, workspaceID, newName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, workspaceID, newName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateWorkspaceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceName'
type Database_UpdateWorkspaceName_Call struct {
	*mock.Call
}

// UpdateWorkspaceName is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - newName string
func (_e *Database_Expecter) UpdateWorkspaceName(ctx interface{}, workspaceID interface{}, newName interface{}) *Database_UpdateWorkspaceName_Call {
	return &Database_UpdateWorkspaceName_Call{Call: _e.mock.On("UpdateWorkspaceName", ctx, workspaceID, newName)}
}

func (_c *Database_UpdateWorkspaceName_Call) Run(run func(ctx context.Context, workspaceID string, newName string)) *Database_UpdateWorkspaceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateWorkspaceName_Call) Return(err error) *Database_UpdateWorkspaceName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateWorkspaceName_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, newName string) error) *Database_UpdateWorkspaceName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceVolumeMeta provides a mock function for the type Database
func (_mock *Database) UpdateWorkspaceVolumeMeta(ctx context.Context, workspaceID string, newMetadata *models.WorkspaceVolumeMetadata) error {
	ret := _mock.Called(ctx, workspaceID, newMetadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceVolumeMeta")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.WorkspaceVolumeMetadata) error); ok {
		r0 = returnFunc(ctx, workspaceID, newMetadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateWorkspaceVolumeMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceVolumeMeta'
type Database_UpdateWorkspaceVolumeMeta_Call struct {
	*mock.Call
}

// UpdateWorkspaceVolumeMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - newMetadata *models.WorkspaceVolumeMetadata
func (_e *Database_Expecter) UpdateWorkspaceVolumeMeta(ctx interface{}, workspaceID interface{}, newMetadata interface{}) *Database_UpdateWorkspaceVolumeMeta_Call {
	return &Database_UpdateWorkspaceVolumeMeta_Call{Call: _e.mock.On("UpdateWorkspaceVolumeMeta", ctx, workspaceID, newMetadata)}
}

func (_c *Database_UpdateWorkspaceVolumeMeta_Call) Run(run func(ctx context.Context, workspaceID string, newMetadata *models.WorkspaceVolumeMetadata)) *Database_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.WorkspaceVolumeMetadata
		if args[2] != nil {
			arg2 = args[2].(*models.WorkspaceVolumeMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateWorkspaceVolumeMeta_Call) Return(err error) *Database_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateWorkspaceVolumeMeta_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, newMetadata *models.WorkspaceVolumeMetadata) error) *Database_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Return(run)
	return _c
}
