// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockartifact

import (
	"context"
	"time"

	"github.com/alwitt/cairn/artifact"
	"github.com/alwitt/cairn/db"
	"github.com/alwitt/cairn/models"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// DeleteArtifact provides a mock function for the type Manager
func (_mock *Manager) DeleteArtifact(ctx context.Context, artifactID string, activeSession db.Database) error {
	ret := _mock.Called(ctx, artifactID, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) error); ok {
		r0 = returnFunc(ctx, artifactID, activeSession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_DeleteArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArtifact'
type Manager_DeleteArtifact_Call struct {
	*mock.Call
}

// DeleteArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - activeSession db.Database
func (_e *Manager_Expecter) DeleteArtifact(ctx interface{}, artifactID interface{}, activeSession interface{}) *Manager_DeleteArtifact_Call {
	return &Manager_DeleteArtifact_Call{Call: _e.mock.On("DeleteArtifact", ctx, artifactID, activeSession)}
}

func (_c *Manager_DeleteArtifact_Call) Run(run func(ctx context.Context, artifactID string, activeSession db.Database)) *Manager_DeleteArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_DeleteArtifact_Call) Return(err error) *Manager_DeleteArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_DeleteArtifact_Call) RunAndReturn(run func(ctx context.Context, artifactID string, activeSession db.Database) error) *Manager_DeleteArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateGetURLForArtifact provides a mock function for the type Manager
func (_mock *Manager) GenerateGetURLForArtifact(ctx context.Context, artifact models.Artifact, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, artifact, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateGetURLForArtifact")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Artifact, time.Duration) (string, error)); ok {
		return returnFunc(ctx, artifact, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Artifact, time.Duration) string); ok {
		r0 = returnFunc(ctx, artifact, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Artifact, time.Duration) error); ok {
		r1 = returnFunc(ctx, artifact, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GenerateGetURLForArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateGetURLForArtifact'
type Manager_GenerateGetURLForArtifact_Call struct {
	*mock.Call
}

// GenerateGetURLForArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifact models.Artifact
//   - ttl time.Duration
func (_e *Manager_Expecter) GenerateGetURLForArtifact(ctx interface{}, artifact interface{}, ttl interface{}) *Manager_GenerateGetURLForArtifact_Call {
	return &Manager_GenerateGetURLForArtifact_Call{Call: _e.mock.On("GenerateGetURLForArtifact", ctx, artifact, ttl)}
}

func (_c *Manager_GenerateGetURLForArtifact_Call) Run(run func(ctx context.Context, artifact models.Artifact, ttl time.Duration)) *Manager_GenerateGetURLForArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Artifact
		if args[1] != nil {
			arg1 = args[1].(models.Artifact)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_GenerateGetURLForArtifact_Call) Return(s string, err error) *Manager_GenerateGetURLForArtifact_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Manager_GenerateGetURLForArtifact_Call) RunAndReturn(run func(ctx context.Context, artifact models.Artifact, ttl time.Duration) (string, error)) *Manager_GenerateGetURLForArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifact provides a mock function for the type Manager
func (_mock *Manager) GetArtifact(ctx context.Context, artifactID string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, artifactID, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, artifactID, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, artifactID, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) error); ok {
		r1 = returnFunc(ctx, artifactID, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifact'
type Manager_GetArtifact_Call struct {
	*mock.Call
}

// GetArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - activeSession db.Database
func (_e *Manager_Expecter) GetArtifact(ctx interface{}, artifactID interface{}, activeSession interface{}) *Manager_GetArtifact_Call {
	return &Manager_GetArtifact_Call{Call: _e.mock.On("GetArtifact", ctx, artifactID, activeSession)}
}

func (_c *Manager_GetArtifact_Call) Run(run func(ctx context.Context, artifactID string, activeSession db.Database)) *Manager_GetArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_GetArtifact_Call) Return(artifact models.Artifact, err error) *Manager_GetArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Manager_GetArtifact_Call) RunAndReturn(run func(ctx context.Context, artifactID string, activeSession db.Database) (models.Artifact, error)) *Manager_GetArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactByName provides a mock function for the type Manager
func (_mock *Manager) GetArtifactByName(ctx context.Context, workspace models.Workspace, name string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, workspace, name, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactByName")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, workspace, name, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, workspace, name, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, string, db.Database) error); ok {
		r1 = returnFunc(ctx, workspace, name, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetArtifactByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactByName'
type Manager_GetArtifactByName_Call struct {
	*mock.Call
}

// GetArtifactByName is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - name string
//   - activeSession db.Database
func (_e *Manager_Expecter) GetArtifactByName(ctx interface{}, workspace interface{}, name interface{}, activeSession interface{}) *Manager_GetArtifactByName_Call {
	return &Manager_GetArtifactByName_Call{Call: _e.mock.On("GetArtifactByName", ctx, workspace, name, activeSession)}
}

func (_c *Manager_GetArtifactByName_Call) Run(run func(ctx context.Context, workspace models.Workspace, name string, activeSession db.Database)) *Manager_GetArtifactByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_GetArtifactByName_Call) Return(artifact models.Artifact, err error) *Manager_GetArtifactByName_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Manager_GetArtifactByName_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, name string, activeSession db.Database) (models.Artifact, error)) *Manager_GetArtifactByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactStagingPutURL provides a mock function for the type Manager
func (_mock *Manager) GetArtifactStagingPutURL(ctx context.Context, workspace models.Workspace, artifactSize int64, b64ArtifactSHA256 string, contentType *string) (artifact.StagingUploadBundle, error) {
	ret := _mock.Called(ctx, workspace, artifactSize, b64ArtifactSHA256, contentType)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactStagingPutURL")
	}

	var r0 artifact.StagingUploadBundle
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, int64, string, *string) (artifact.StagingUploadBundle, error)); ok {
		return returnFunc(ctx, workspace, artifactSize, b64ArtifactSHA256, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, int64, string, *string) artifact.StagingUploadBundle); ok {
		r0 = returnFunc(ctx, workspace, artifactSize, b64ArtifactSHA256, contentType)
	} else {
		r0 = ret.Get(0).(artifact.StagingUploadBundle)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, int64, string, *string) error); ok {
		r1 = returnFunc(ctx, workspace, artifactSize, b64ArtifactSHA256, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_GetArtifactStagingPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactStagingPutURL'
type Manager_GetArtifactStagingPutURL_Call struct {
	*mock.Call
}

// GetArtifactStagingPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - artifactSize int64
//   - b64ArtifactSHA256 string
//   - contentType *string
func (_e *Manager_Expecter) GetArtifactStagingPutURL(ctx interface{}, workspace interface{}, artifactSize interface{}, b64ArtifactSHA256 interface{}, contentType interface{}) *Manager_GetArtifactStagingPutURL_Call {
	return &Manager_GetArtifactStagingPutURL_Call{Call: _e.mock.On("GetArtifactStagingPutURL", ctx, workspace, artifactSize, b64ArtifactSHA256, contentType)}
}

func (_c *Manager_GetArtifactStagingPutURL_Call) Run(run func(ctx context.Context, workspace models.Workspace, artifactSize int64, b64ArtifactSHA256 string, contentType *string)) *Manager_GetArtifactStagingPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Manager_GetArtifactStagingPutURL_Call) Return(stagingUploadBundle artifact.StagingUploadBundle, err error) *Manager_GetArtifactStagingPutURL_Call {
	_c.Call.Return(stagingUploadBundle, err)
	return _c
}

func (_c *Manager_GetArtifactStagingPutURL_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, artifactSize int64, b64ArtifactSHA256 string, contentType *string) (artifact.StagingUploadBundle, error)) *Manager_GetArtifactStagingPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaceArtifacts provides a mock function for the type Manager
func (_mock *Manager) ListWorkspaceArtifacts(ctx context.Context, workspace models.Workspace, filters db.ArtifactQueryFilter, activeSession db.Database) ([]models.Artifact, error) {
	ret := _mock.Called(ctx, workspace, filters, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaceArtifacts")
	}

	var r0 []models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, db.ArtifactQueryFilter, db.Database) ([]models.Artifact, error)); ok {
		return returnFunc(ctx, workspace, filters, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, db.ArtifactQueryFilter, db.Database) []models.Artifact); ok {
		r0 = returnFunc(ctx, workspace, filters, activeSession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artifact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, db.ArtifactQueryFilter, db.Database) error); ok {
		r1 = returnFunc(ctx, workspace, filters, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_ListWorkspaceArtifacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaceArtifacts'
type Manager_ListWorkspaceArtifacts_Call struct {
	*mock.Call
}

// ListWorkspaceArtifacts is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - filters db.ArtifactQueryFilter
//   - activeSession db.Database
func (_e *Manager_Expecter) ListWorkspaceArtifacts(ctx interface{}, workspace interface{}, filters interface{}, activeSession interface{}) *Manager_ListWorkspaceArtifacts_Call {
	return &Manager_ListWorkspaceArtifacts_Call{Call: _e.mock.On("ListWorkspaceArtifacts", ctx, workspace, filters, activeSession)}
}

func (_c *Manager_ListWorkspaceArtifacts_Call) Run(run func(ctx context.Context, workspace models.Workspace, filters db.ArtifactQueryFilter, activeSession db.Database)) *Manager_ListWorkspaceArtifacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 db.ArtifactQueryFilter
		if args[2] != nil {
			arg2 = args[2].(db.ArtifactQueryFilter)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_ListWorkspaceArtifacts_Call) Return(artifacts []models.Artifact, err error) *Manager_ListWorkspaceArtifacts_Call {
	_c.Call.Return(artifacts, err)
	return _c
}

func (_c *Manager_ListWorkspaceArtifacts_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, filters db.ArtifactQueryFilter, activeSession db.Database) ([]models.Artifact, error)) *Manager_ListWorkspaceArtifacts_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterNewArtifact provides a mock function for the type Manager
func (_mock *Manager) RegisterNewArtifact(ctx context.Context, workspace models.Workspace, stagingObjKey string, name string, description *string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, workspace, stagingObjKey, name, description, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for RegisterNewArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, string, *string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, workspace, stagingObjKey, name, description, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, string, *string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, workspace, stagingObjKey, name, description, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, string, string, *string, db.Database) error); ok {
		r1 = returnFunc(ctx, workspace, stagingObjKey, name, description, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_RegisterNewArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterNewArtifact'
type Manager_RegisterNewArtifact_Call struct {
	*mock.Call
}

// RegisterNewArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - stagingObjKey string
//   - name string
//   - description *string
//   - activeSession db.Database
func (_e *Manager_Expecter) RegisterNewArtifact(ctx interface{}, workspace interface{}, stagingObjKey interface{}, name interface{}, description interface{}, activeSession interface{}) *Manager_RegisterNewArtifact_Call {
	return &Manager_RegisterNewArtifact_Call{Call: _e.mock.On("RegisterNewArtifact", ctx, workspace, stagingObjKey, name, description, activeSession)}
}

func (_c *Manager_RegisterNewArtifact_Call) Run(run func(ctx context.Context, workspace models.Workspace, stagingObjKey string, name string, description *string, activeSession db.Database)) *Manager_RegisterNewArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 db.Database
		if args[5] != nil {
			arg5 = args[5].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Manager_RegisterNewArtifact_Call) Return(artifact1 models.Artifact, err error) *Manager_RegisterNewArtifact_Call {
	_c.Call.Return(artifact1, err)
	return _c
}

func (_c *Manager_RegisterNewArtifact_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, stagingObjKey string, name string, description *string, activeSession db.Database) (models.Artifact, error)) *Manager_RegisterNewArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// RenameArtifact provides a mock function for the type Manager
func (_mock *Manager) RenameArtifact(ctx context.Context, artifactID string, newName string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, artifactID, newName, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for RenameArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, artifactID, newName, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, artifactID, newName, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, db.Database) error); ok {
		r1 = returnFunc(ctx, artifactID, newName, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_RenameArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameArtifact'
type Manager_RenameArtifact_Call struct {
	*mock.Call
}

// RenameArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - newName string
//   - activeSession db.Database
func (_e *Manager_Expecter) RenameArtifact(ctx interface{}, artifactID interface{}, newName interface{}, activeSession interface{}) *Manager_RenameArtifact_Call {
	return &Manager_RenameArtifact_Call{Call: _e.mock.On("RenameArtifact", ctx, artifactID, newName, activeSession)}
}

func (_c *Manager_RenameArtifact_Call) Run(run func(ctx context.Context, artifactID string, newName string, activeSession db.Database)) *Manager_RenameArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_RenameArtifact_Call) Return(artifact1 models.Artifact, err error) *Manager_RenameArtifact_Call {
	_c.Call.Return(artifact1, err)
	return _c
}

func (_c *Manager_RenameArtifact_Call) RunAndReturn(run func(ctx context.Context, artifactID string, newName string, activeSession db.Database) (models.Artifact, error)) *Manager_RenameArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactContent provides a mock function for the type Manager
func (_mock *Manager) UpdateArtifactContent(ctx context.Context, artifact1 models.Artifact, stagingObjKey string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, artifact1, stagingObjKey, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactContent")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Artifact, string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, artifact1, stagingObjKey, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Artifact, string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, artifact1, stagingObjKey, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Artifact, string, db.Database) error); ok {
		r1 = returnFunc(ctx, artifact1, stagingObjKey, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_UpdateArtifactContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactContent'
type Manager_UpdateArtifactContent_Call struct {
	*mock.Call
}

// UpdateArtifactContent is a helper method to define mock.On call
//   - ctx context.Context
//   - artifact1 models.Artifact
//   - stagingObjKey string
//   - activeSession db.Database
func (_e *Manager_Expecter) UpdateArtifactContent(ctx interface{}, artifact1 interface{}, stagingObjKey interface{}, activeSession interface{}) *Manager_UpdateArtifactContent_Call {
	return &Manager_UpdateArtifactContent_Call{Call: _e.mock.On("UpdateArtifactContent", ctx, artifact1, stagingObjKey, activeSession)}
}

func (_c *Manager_UpdateArtifactContent_Call) Run(run func(ctx context.Context, artifact1 models.Artifact, stagingObjKey string, activeSession db.Database)) *Manager_UpdateArtifactContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Artifact
		if args[1] != nil {
			arg1 = args[1].(models.Artifact)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_UpdateArtifactContent_Call) Return(artifact11 models.Artifact, err error) *Manager_UpdateArtifactContent_Call {
	_c.Call.Return(artifact11, err)
	return _c
}

func (_c *Manager_UpdateArtifactContent_Call) RunAndReturn(run func(ctx context.Context, artifact1 models.Artifact, stagingObjKey string, activeSession db.Database) (models.Artifact, error)) *Manager_UpdateArtifactContent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifactDescription provides a mock function for the type Manager
func (_mock *Manager) UpdateArtifactDescription(ctx context.Context, artifactID string, newDescription *string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, artifactID, newDescription, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifactDescription")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, artifactID, newDescription, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, artifactID, newDescription, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, db.Database) error); ok {
		r1 = returnFunc(ctx, artifactID, newDescription, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_UpdateArtifactDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifactDescription'
type Manager_UpdateArtifactDescription_Call struct {
	*mock.Call
}

// UpdateArtifactDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - artifactID string
//   - newDescription *string
//   - activeSession db.Database
func (_e *Manager_Expecter) UpdateArtifactDescription(ctx interface{}, artifactID interface{}, newDescription interface{}, activeSession interface{}) *Manager_UpdateArtifactDescription_Call {
	return &Manager_UpdateArtifactDescription_Call{Call: _e.mock.On("UpdateArtifactDescription", ctx, artifactID, newDescription, activeSession)}
}

func (_c *Manager_UpdateArtifactDescription_Call) Run(run func(ctx context.Context, artifactID string, newDescription *string, activeSession db.Database)) *Manager_UpdateArtifactDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_UpdateArtifactDescription_Call) Return(artifact1 models.Artifact, err error) *Manager_UpdateArtifactDescription_Call {
	_c.Call.Return(artifact1, err)
	return _c
}

func (_c *Manager_UpdateArtifactDescription_Call) RunAndReturn(run func(ctx context.Context, artifactID string, newDescription *string, activeSession db.Database) (models.Artifact, error)) *Manager_UpdateArtifactDescription_Call {
	_c.Call.Return(run)
	return _c
}
