// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockartifact

import (
	"context"

	"github.com/alwitt/cairn/db"
	"github.com/alwitt/cairn/models"
	mock "github.com/stretchr/testify/mock"
)

// NewOperator creates a new instance of Operator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Operator {
	mock := &Operator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Operator is an autogenerated mock type for the Operator type
type Operator struct {
	mock.Mock
}

type Operator_Expecter struct {
	mock *mock.Mock
}

func (_m *Operator) EXPECT() *Operator_Expecter {
	return &Operator_Expecter{mock: &_m.Mock}
}

// DownloadArtifact provides a mock function for the type Operator
func (_mock *Operator) DownloadArtifact(ctx context.Context, workspace models.Workspace, artifact models.Artifact, targetPath string) error {
	ret := _mock.Called(ctx, workspace, artifact, targetPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadArtifact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, models.Artifact, string) error); ok {
		r0 = returnFunc(ctx, workspace, artifact, targetPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Operator_DownloadArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadArtifact'
type Operator_DownloadArtifact_Call struct {
	*mock.Call
}

// DownloadArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - artifact models.Artifact
//   - targetPath string
func (_e *Operator_Expecter) DownloadArtifact(ctx interface{}, workspace interface{}, artifact interface{}, targetPath interface{}) *Operator_DownloadArtifact_Call {
	return &Operator_DownloadArtifact_Call{Call: _e.mock.On("DownloadArtifact", ctx, workspace, artifact, targetPath)}
}

func (_c *Operator_DownloadArtifact_Call) Run(run func(ctx context.Context, workspace models.Workspace, artifact models.Artifact, targetPath string)) *Operator_DownloadArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 models.Artifact
		if args[2] != nil {
			arg2 = args[2].(models.Artifact)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Operator_DownloadArtifact_Call) Return(err error) *Operator_DownloadArtifact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Operator_DownloadArtifact_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, artifact models.Artifact, targetPath string) error) *Operator_DownloadArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateArtifact provides a mock function for the type Operator
func (_mock *Operator) UpdateArtifact(ctx context.Context, workspace models.Workspace, artifact models.Artifact, sourcePath string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, workspace, artifact, sourcePath, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, models.Artifact, string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, workspace, artifact, sourcePath, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, models.Artifact, string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, workspace, artifact, sourcePath, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, models.Artifact, string, db.Database) error); ok {
		r1 = returnFunc(ctx, workspace, artifact, sourcePath, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Operator_UpdateArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateArtifact'
type Operator_UpdateArtifact_Call struct {
	*mock.Call
}

// UpdateArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - artifact models.Artifact
//   - sourcePath string
//   - activeSession db.Database
func (_e *Operator_Expecter) UpdateArtifact(ctx interface{}, workspace interface{}, artifact interface{}, sourcePath interface{}, activeSession interface{}) *Operator_UpdateArtifact_Call {
	return &Operator_UpdateArtifact_Call{Call: _e.mock.On("UpdateArtifact", ctx, workspace, artifact, sourcePath, activeSession)}
}

func (_c *Operator_UpdateArtifact_Call) Run(run func(ctx context.Context, workspace models.Workspace, artifact models.Artifact, sourcePath string, activeSession db.Database)) *Operator_UpdateArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 models.Artifact
		if args[2] != nil {
			arg2 = args[2].(models.Artifact)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 db.Database
		if args[4] != nil {
			arg4 = args[4].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Operator_UpdateArtifact_Call) Return(artifact1 models.Artifact, err error) *Operator_UpdateArtifact_Call {
	_c.Call.Return(artifact1, err)
	return _c
}

func (_c *Operator_UpdateArtifact_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, artifact models.Artifact, sourcePath string, activeSession db.Database) (models.Artifact, error)) *Operator_UpdateArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// UploadArtifact provides a mock function for the type Operator
func (_mock *Operator) UploadArtifact(ctx context.Context, workspace models.Workspace, sourcePath string, name string, description *string, activeSession db.Database) (models.Artifact, error) {
	ret := _mock.Called(ctx, workspace, sourcePath, name, description, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UploadArtifact")
	}

	var r0 models.Artifact
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, string, *string, db.Database) (models.Artifact, error)); ok {
		return returnFunc(ctx, workspace, sourcePath, name, description, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, string, string, *string, db.Database) models.Artifact); ok {
		r0 = returnFunc(ctx, workspace, sourcePath, name, description, activeSession)
	} else {
		r0 = ret.Get(0).(models.Artifact)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Workspace, string, string, *string, db.Database) error); ok {
		r1 = returnFunc(ctx, workspace, sourcePath, name, description, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Operator_UploadArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadArtifact'
type Operator_UploadArtifact_Call struct {
	*mock.Call
}

// UploadArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - sourcePath string
//   - name string
//   - description *string
//   - activeSession db.Database
func (_e *Operator_Expecter) UploadArtifact(ctx interface{}, workspace interface{}, sourcePath interface{}, name interface{}, description interface{}, activeSession interface{}) *Operator_UploadArtifact_Call {
	return &Operator_UploadArtifact_Call{Call: _e.mock.On("UploadArtifact", ctx, workspace, sourcePath, name, description, activeSession)}
}

func (_c *Operator_UploadArtifact_Call) Run(run func(ctx context.Context, workspace models.Workspace, sourcePath string, name string, description *string, activeSession db.Database)) *Operator_UploadArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 db.Database
		if args[5] != nil {
			arg5 = args[5].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Operator_UploadArtifact_Call) Return(artifact models.Artifact, err error) *Operator_UploadArtifact_Call {
	_c.Call.Return(artifact, err)
	return _c
}

func (_c *Operator_UploadArtifact_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, sourcePath string, name string, description *string, activeSession db.Database) (models.Artifact, error)) *Operator_UploadArtifact_Call {
	_c.Call.Return(run)
	return _c
}
