// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnitTestCallbackCollector creates a new instance of UnitTestCallbackCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitTestCallbackCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitTestCallbackCollector {
	mock := &UnitTestCallbackCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnitTestCallbackCollector is an autogenerated mock type for the UnitTestCallbackCollector type
type UnitTestCallbackCollector struct {
	mock.Mock
}

type UnitTestCallbackCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitTestCallbackCollector) EXPECT() *UnitTestCallbackCollector_Expecter {
	return &UnitTestCallbackCollector_Expecter{mock: &_m.Mock}
}

// EstimateMIMEType provides a mock function for the type UnitTestCallbackCollector
func (_mock *UnitTestCallbackCollector) EstimateMIMEType(data []byte) string {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for EstimateMIMEType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// UnitTestCallbackCollector_EstimateMIMEType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateMIMEType'
type UnitTestCallbackCollector_EstimateMIMEType_Call struct {
	*mock.Call
}

// EstimateMIMEType is a helper method to define mock.On call
//   - data []byte
func (_e *UnitTestCallbackCollector_Expecter) EstimateMIMEType(data interface{}) *UnitTestCallbackCollector_EstimateMIMEType_Call {
	return &UnitTestCallbackCollector_EstimateMIMEType_Call{Call: _e.mock.On("EstimateMIMEType", data)}
}

func (_c *UnitTestCallbackCollector_EstimateMIMEType_Call) Run(run func(data []byte)) *UnitTestCallbackCollector_EstimateMIMEType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UnitTestCallbackCollector_EstimateMIMEType_Call) Return(s string) *UnitTestCallbackCollector_EstimateMIMEType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *UnitTestCallbackCollector_EstimateMIMEType_Call) RunAndReturn(run func(data []byte) string) *UnitTestCallbackCollector_EstimateMIMEType_Call {
	_c.Call.Return(run)
	return _c
}
