// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockworkspace

import (
	"context"

	"github.com/alwitt/cairn/db"
	"github.com/alwitt/cairn/models"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// DefineNewWorkspace provides a mock function for the type Manager
func (_mock *Manager) DefineNewWorkspace(ctx context.Context, name string, description *string, volumeMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database) (models.Workspace, error) {
	ret := _mock.Called(ctx, name, description, volumeMetadata, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewWorkspace")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *models.WorkspaceVolumeMetadata, db.Database) (models.Workspace, error)); ok {
		return returnFunc(ctx, name, description, volumeMetadata, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *models.WorkspaceVolumeMetadata, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, name, description, volumeMetadata, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, *models.WorkspaceVolumeMetadata, db.Database) error); ok {
		r1 = returnFunc(ctx, name, description, volumeMetadata, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_DefineNewWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewWorkspace'
type Manager_DefineNewWorkspace_Call struct {
	*mock.Call
}

// DefineNewWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - volumeMetadata *models.WorkspaceVolumeMetadata
//   - activeSession db.Database
func (_e *Manager_Expecter) DefineNewWorkspace(ctx interface{}, name interface{}, description interface{}, volumeMetadata interface{}, activeSession interface{}) *Manager_DefineNewWorkspace_Call {
	return &Manager_DefineNewWorkspace_Call{Call: _e.mock.On("DefineNewWorkspace", ctx, name, description, volumeMetadata, activeSession)}
}

func (_c *Manager_DefineNewWorkspace_Call) Run(run func(ctx context.Context, name string, description *string, volumeMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database)) *Manager_DefineNewWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *models.WorkspaceVolumeMetadata
		if args[3] != nil {
			arg3 = args[3].(*models.WorkspaceVolumeMetadata)
		}
		var arg4 db.Database
		if args[4] != nil {
			arg4 = args[4].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Manager_DefineNewWorkspace_Call) Return(workspace models.Workspace, err error) *Manager_DefineNewWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Manager_DefineNewWorkspace_Call) RunAndReturn(run func(ctx context.Context, name string, description *string, volumeMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database) (models.Workspace, error)) *Manager_DefineNewWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function for the type Manager
func (_mock *Manager) DeleteWorkspace(ctx context.Context, workspaceID string, activeSession db.Database) error {
	ret := _mock.Called(ctx, workspaceID, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) error); ok {
		r0 = returnFunc(ctx, workspaceID, activeSession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type Manager_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - activeSession db.Database
func (_e *Manager_Expecter) DeleteWorkspace(ctx interface{}, workspaceID interface{}, activeSession interface{}) *Manager_DeleteWorkspace_Call {
	return &Manager_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", ctx, workspaceID, activeSession)}
}

func (_c *Manager_DeleteWorkspace_Call) Run(run func(ctx context.Context, workspaceID string, activeSession db.Database)) *Manager_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_DeleteWorkspace_Call) Return(err error) *Manager_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_DeleteWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, activeSession db.Database) error) *Manager_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type Manager
func (_mock *Manager) GetWorkspace(ctx context.Context, id string, activeSession db.Database) (models.Workspace, int, error) {
	ret := _mock.Called(ctx, id, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 models.Workspace
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.Workspace, int, error)); ok {
		return returnFunc(ctx, id, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, id, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) int); ok {
		r1 = returnFunc(ctx, id, activeSession)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, db.Database) error); ok {
		r2 = returnFunc(ctx, id, activeSession)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type Manager_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - activeSession db.Database
func (_e *Manager_Expecter) GetWorkspace(ctx interface{}, id interface{}, activeSession interface{}) *Manager_GetWorkspace_Call {
	return &Manager_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", ctx, id, activeSession)}
}

func (_c *Manager_GetWorkspace_Call) Run(run func(ctx context.Context, id string, activeSession db.Database)) *Manager_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_GetWorkspace_Call) Return(workspace models.Workspace, n int, err error) *Manager_GetWorkspace_Call {
	_c.Call.Return(workspace, n, err)
	return _c
}

func (_c *Manager_GetWorkspace_Call) RunAndReturn(run func(ctx context.Context, id string, activeSession db.Database) (models.Workspace, int, error)) *Manager_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspaceByName provides a mock function for the type Manager
func (_mock *Manager) GetWorkspaceByName(ctx context.Context, name string, activeSession db.Database) (models.Workspace, int, error) {
	ret := _mock.Called(ctx, name, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceByName")
	}

	var r0 models.Workspace
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) (models.Workspace, int, error)); ok {
		return returnFunc(ctx, name, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, name, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.Database) int); ok {
		r1 = returnFunc(ctx, name, activeSession)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, db.Database) error); ok {
		r2 = returnFunc(ctx, name, activeSession)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Manager_GetWorkspaceByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspaceByName'
type Manager_GetWorkspaceByName_Call struct {
	*mock.Call
}

// GetWorkspaceByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - activeSession db.Database
func (_e *Manager_Expecter) GetWorkspaceByName(ctx interface{}, name interface{}, activeSession interface{}) *Manager_GetWorkspaceByName_Call {
	return &Manager_GetWorkspaceByName_Call{Call: _e.mock.On("GetWorkspaceByName", ctx, name, activeSession)}
}

func (_c *Manager_GetWorkspaceByName_Call) Run(run func(ctx context.Context, name string, activeSession db.Database)) *Manager_GetWorkspaceByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_GetWorkspaceByName_Call) Return(workspace models.Workspace, n int, err error) *Manager_GetWorkspaceByName_Call {
	_c.Call.Return(workspace, n, err)
	return _c
}

func (_c *Manager_GetWorkspaceByName_Call) RunAndReturn(run func(ctx context.Context, name string, activeSession db.Database) (models.Workspace, int, error)) *Manager_GetWorkspaceByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaceVolumes provides a mock function for the type Manager
func (_mock *Manager) ListWorkspaceVolumes(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaceVolumes")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_ListWorkspaceVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaceVolumes'
type Manager_ListWorkspaceVolumes_Call struct {
	*mock.Call
}

// ListWorkspaceVolumes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Manager_Expecter) ListWorkspaceVolumes(ctx interface{}) *Manager_ListWorkspaceVolumes_Call {
	return &Manager_ListWorkspaceVolumes_Call{Call: _e.mock.On("ListWorkspaceVolumes", ctx)}
}

func (_c *Manager_ListWorkspaceVolumes_Call) Run(run func(ctx context.Context)) *Manager_ListWorkspaceVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_ListWorkspaceVolumes_Call) Return(strings []string, err error) *Manager_ListWorkspaceVolumes_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Manager_ListWorkspaceVolumes_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *Manager_ListWorkspaceVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspaces provides a mock function for the type Manager
func (_mock *Manager) ListWorkspaces(ctx context.Context, filters db.WorkspaceQueryFilter, activeSession db.Database) ([]models.Workspace, error) {
	ret := _mock.Called(ctx, filters, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspaces")
	}

	var r0 []models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.WorkspaceQueryFilter, db.Database) ([]models.Workspace, error)); ok {
		return returnFunc(ctx, filters, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.WorkspaceQueryFilter, db.Database) []models.Workspace); ok {
		r0 = returnFunc(ctx, filters, activeSession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.WorkspaceQueryFilter, db.Database) error); ok {
		r1 = returnFunc(ctx, filters, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_ListWorkspaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspaces'
type Manager_ListWorkspaces_Call struct {
	*mock.Call
}

// ListWorkspaces is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.WorkspaceQueryFilter
//   - activeSession db.Database
func (_e *Manager_Expecter) ListWorkspaces(ctx interface{}, filters interface{}, activeSession interface{}) *Manager_ListWorkspaces_Call {
	return &Manager_ListWorkspaces_Call{Call: _e.mock.On("ListWorkspaces", ctx, filters, activeSession)}
}

func (_c *Manager_ListWorkspaces_Call) Run(run func(ctx context.Context, filters db.WorkspaceQueryFilter, activeSession db.Database)) *Manager_ListWorkspaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.WorkspaceQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.WorkspaceQueryFilter)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_ListWorkspaces_Call) Return(workspaces []models.Workspace, err error) *Manager_ListWorkspaces_Call {
	_c.Call.Return(workspaces, err)
	return _c
}

func (_c *Manager_ListWorkspaces_Call) RunAndReturn(run func(ctx context.Context, filters db.WorkspaceQueryFilter, activeSession db.Database) ([]models.Workspace, error)) *Manager_ListWorkspaces_Call {
	_c.Call.Return(run)
	return _c
}

// SetupWorkspaceVolume provides a mock function for the type Manager
func (_mock *Manager) SetupWorkspaceVolume(ctx context.Context, workspace models.Workspace, activeSession db.Database) error {
	ret := _mock.Called(ctx, workspace, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for SetupWorkspaceVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, db.Database) error); ok {
		r0 = returnFunc(ctx, workspace, activeSession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_SetupWorkspaceVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupWorkspaceVolume'
type Manager_SetupWorkspaceVolume_Call struct {
	*mock.Call
}

// SetupWorkspaceVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - activeSession db.Database
func (_e *Manager_Expecter) SetupWorkspaceVolume(ctx interface{}, workspace interface{}, activeSession interface{}) *Manager_SetupWorkspaceVolume_Call {
	return &Manager_SetupWorkspaceVolume_Call{Call: _e.mock.On("SetupWorkspaceVolume", ctx, workspace, activeSession)}
}

func (_c *Manager_SetupWorkspaceVolume_Call) Run(run func(ctx context.Context, workspace models.Workspace, activeSession db.Database)) *Manager_SetupWorkspaceVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_SetupWorkspaceVolume_Call) Return(err error) *Manager_SetupWorkspaceVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_SetupWorkspaceVolume_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, activeSession db.Database) error) *Manager_SetupWorkspaceVolume_Call {
	_c.Call.Return(run)
	return _c
}

// TeardownWorkspaceVolume provides a mock function for the type Manager
func (_mock *Manager) TeardownWorkspaceVolume(ctx context.Context, workspace models.Workspace, activeSession db.Database) error {
	ret := _mock.Called(ctx, workspace, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for TeardownWorkspaceVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workspace, db.Database) error); ok {
		r0 = returnFunc(ctx, workspace, activeSession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_TeardownWorkspaceVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TeardownWorkspaceVolume'
type Manager_TeardownWorkspaceVolume_Call struct {
	*mock.Call
}

// TeardownWorkspaceVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace models.Workspace
//   - activeSession db.Database
func (_e *Manager_Expecter) TeardownWorkspaceVolume(ctx interface{}, workspace interface{}, activeSession interface{}) *Manager_TeardownWorkspaceVolume_Call {
	return &Manager_TeardownWorkspaceVolume_Call{Call: _e.mock.On("TeardownWorkspaceVolume", ctx, workspace, activeSession)}
}

func (_c *Manager_TeardownWorkspaceVolume_Call) Run(run func(ctx context.Context, workspace models.Workspace, activeSession db.Database)) *Manager_TeardownWorkspaceVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workspace
		if args[1] != nil {
			arg1 = args[1].(models.Workspace)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_TeardownWorkspaceVolume_Call) Return(err error) *Manager_TeardownWorkspaceVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_TeardownWorkspaceVolume_Call) RunAndReturn(run func(ctx context.Context, workspace models.Workspace, activeSession db.Database) error) *Manager_TeardownWorkspaceVolume_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceDescription provides a mock function for the type Manager
func (_mock *Manager) UpdateWorkspaceDescription(ctx context.Context, id string, newDescription *string, activeSession db.Database) (models.Workspace, error) {
	ret := _mock.Called(ctx, id, newDescription, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceDescription")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, db.Database) (models.Workspace, error)); ok {
		return returnFunc(ctx, id, newDescription, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, id, newDescription, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, db.Database) error); ok {
		r1 = returnFunc(ctx, id, newDescription, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_UpdateWorkspaceDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceDescription'
type Manager_UpdateWorkspaceDescription_Call struct {
	*mock.Call
}

// UpdateWorkspaceDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newDescription *string
//   - activeSession db.Database
func (_e *Manager_Expecter) UpdateWorkspaceDescription(ctx interface{}, id interface{}, newDescription interface{}, activeSession interface{}) *Manager_UpdateWorkspaceDescription_Call {
	return &Manager_UpdateWorkspaceDescription_Call{Call: _e.mock.On("UpdateWorkspaceDescription", ctx, id, newDescription, activeSession)}
}

func (_c *Manager_UpdateWorkspaceDescription_Call) Run(run func(ctx context.Context, id string, newDescription *string, activeSession db.Database)) *Manager_UpdateWorkspaceDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_UpdateWorkspaceDescription_Call) Return(workspace models.Workspace, err error) *Manager_UpdateWorkspaceDescription_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Manager_UpdateWorkspaceDescription_Call) RunAndReturn(run func(ctx context.Context, id string, newDescription *string, activeSession db.Database) (models.Workspace, error)) *Manager_UpdateWorkspaceDescription_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceName provides a mock function for the type Manager
func (_mock *Manager) UpdateWorkspaceName(ctx context.Context, id string, newName string, activeSession db.Database) (models.Workspace, error) {
	ret := _mock.Called(ctx, id, newName, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceName")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, db.Database) (models.Workspace, error)); ok {
		return returnFunc(ctx, id, newName, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, id, newName, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, db.Database) error); ok {
		r1 = returnFunc(ctx, id, newName, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_UpdateWorkspaceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceName'
type Manager_UpdateWorkspaceName_Call struct {
	*mock.Call
}

// UpdateWorkspaceName is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newName string
//   - activeSession db.Database
func (_e *Manager_Expecter) UpdateWorkspaceName(ctx interface{}, id interface{}, newName interface{}, activeSession interface{}) *Manager_UpdateWorkspaceName_Call {
	return &Manager_UpdateWorkspaceName_Call{Call: _e.mock.On("UpdateWorkspaceName", ctx, id, newName, activeSession)}
}

func (_c *Manager_UpdateWorkspaceName_Call) Run(run func(ctx context.Context, id string, newName string, activeSession db.Database)) *Manager_UpdateWorkspaceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_UpdateWorkspaceName_Call) Return(workspace models.Workspace, err error) *Manager_UpdateWorkspaceName_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Manager_UpdateWorkspaceName_Call) RunAndReturn(run func(ctx context.Context, id string, newName string, activeSession db.Database) (models.Workspace, error)) *Manager_UpdateWorkspaceName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspaceVolumeMeta provides a mock function for the type Manager
func (_mock *Manager) UpdateWorkspaceVolumeMeta(ctx context.Context, id string, newMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database) (models.Workspace, error) {
	ret := _mock.Called(ctx, id, newMetadata, activeSession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceVolumeMeta")
	}

	var r0 models.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.WorkspaceVolumeMetadata, db.Database) (models.Workspace, error)); ok {
		return returnFunc(ctx, id, newMetadata, activeSession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *models.WorkspaceVolumeMetadata, db.Database) models.Workspace); ok {
		r0 = returnFunc(ctx, id, newMetadata, activeSession)
	} else {
		r0 = ret.Get(0).(models.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *models.WorkspaceVolumeMetadata, db.Database) error); ok {
		r1 = returnFunc(ctx, id, newMetadata, activeSession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_UpdateWorkspaceVolumeMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspaceVolumeMeta'
type Manager_UpdateWorkspaceVolumeMeta_Call struct {
	*mock.Call
}

// UpdateWorkspaceVolumeMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - newMetadata *models.WorkspaceVolumeMetadata
//   - activeSession db.Database
func (_e *Manager_Expecter) UpdateWorkspaceVolumeMeta(ctx interface{}, id interface{}, newMetadata interface{}, activeSession interface{}) *Manager_UpdateWorkspaceVolumeMeta_Call {
	return &Manager_UpdateWorkspaceVolumeMeta_Call{Call: _e.mock.On("UpdateWorkspaceVolumeMeta", ctx, id, newMetadata, activeSession)}
}

func (_c *Manager_UpdateWorkspaceVolumeMeta_Call) Run(run func(ctx context.Context, id string, newMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database)) *Manager_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *models.WorkspaceVolumeMetadata
		if args[2] != nil {
			arg2 = args[2].(*models.WorkspaceVolumeMetadata)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Manager_UpdateWorkspaceVolumeMeta_Call) Return(workspace models.Workspace, err error) *Manager_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *Manager_UpdateWorkspaceVolumeMeta_Call) RunAndReturn(run func(ctx context.Context, id string, newMetadata *models.WorkspaceVolumeMetadata, activeSession db.Database) (models.Workspace, error)) *Manager_UpdateWorkspaceVolumeMeta_Call {
	_c.Call.Return(run)
	return _c
}
