// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmaintenance

import (
	"context"
	"time"

	"github.com/alwitt/cairn/maintenance"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// DeleteOrphanedStagingObjects provides a mock function for the type Manager
func (_mock *Manager) DeleteOrphanedStagingObjects(ctx context.Context, timestamp time.Time, workspaceID *string) (maintenance.StagingReapReport, error) {
	ret := _mock.Called(ctx, timestamp, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrphanedStagingObjects")
	}

	var r0 maintenance.StagingReapReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *string) (maintenance.StagingReapReport, error)); ok {
		return returnFunc(ctx, timestamp, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *string) maintenance.StagingReapReport); ok {
		r0 = returnFunc(ctx, timestamp, workspaceID)
	} else {
		r0 = ret.Get(0).(maintenance.StagingReapReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, *string) error); ok {
		r1 = returnFunc(ctx, timestamp, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_DeleteOrphanedStagingObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrphanedStagingObjects'
type Manager_DeleteOrphanedStagingObjects_Call struct {
	*mock.Call
}

// DeleteOrphanedStagingObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - timestamp time.Time
//   - workspaceID *string
func (_e *Manager_Expecter) DeleteOrphanedStagingObjects(ctx interface{}, timestamp interface{}, workspaceID interface{}) *Manager_DeleteOrphanedStagingObjects_Call {
	return &Manager_DeleteOrphanedStagingObjects_Call{Call: _e.mock.On("DeleteOrphanedStagingObjects", ctx, timestamp, workspaceID)}
}

func (_c *Manager_DeleteOrphanedStagingObjects_Call) Run(run func(ctx context.Context, timestamp time.Time, workspaceID *string)) *Manager_DeleteOrphanedStagingObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_DeleteOrphanedStagingObjects_Call) Return(stagingReapReport maintenance.StagingReapReport, err error) *Manager_DeleteOrphanedStagingObjects_Call {
	_c.Call.Return(stagingReapReport, err)
	return _c
}

func (_c *Manager_DeleteOrphanedStagingObjects_Call) RunAndReturn(run func(ctx context.Context, timestamp time.Time, workspaceID *string) (maintenance.StagingReapReport, error)) *Manager_DeleteOrphanedStagingObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileStorageObjects provides a mock function for the type Manager
func (_mock *Manager) ReconcileStorageObjects(ctx context.Context, timestamp time.Time, workspaceID *string) (maintenance.StorageReconcileReport, error) {
	ret := _mock.Called(ctx, timestamp, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileStorageObjects")
	}

	var r0 maintenance.StorageReconcileReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *string) (maintenance.StorageReconcileReport, error)); ok {
		return returnFunc(ctx, timestamp, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *string) maintenance.StorageReconcileReport); ok {
		r0 = returnFunc(ctx, timestamp, workspaceID)
	} else {
		r0 = ret.Get(0).(maintenance.StorageReconcileReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, *string) error); ok {
		r1 = returnFunc(ctx, timestamp, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_ReconcileStorageObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileStorageObjects'
type Manager_ReconcileStorageObjects_Call struct {
	*mock.Call
}

// ReconcileStorageObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - timestamp time.Time
//   - workspaceID *string
func (_e *Manager_Expecter) ReconcileStorageObjects(ctx interface{}, timestamp interface{}, workspaceID interface{}) *Manager_ReconcileStorageObjects_Call {
	return &Manager_ReconcileStorageObjects_Call{Call: _e.mock.On("ReconcileStorageObjects", ctx, timestamp, workspaceID)}
}

func (_c *Manager_ReconcileStorageObjects_Call) Run(run func(ctx context.Context, timestamp time.Time, workspaceID *string)) *Manager_ReconcileStorageObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Manager_ReconcileStorageObjects_Call) Return(storageReconcileReport maintenance.StorageReconcileReport, err error) *Manager_ReconcileStorageObjects_Call {
	_c.Call.Return(storageReconcileReport, err)
	return _c
}

func (_c *Manager_ReconcileStorageObjects_Call) RunAndReturn(run func(ctx context.Context, timestamp time.Time, workspaceID *string) (maintenance.StorageReconcileReport, error)) *Manager_ReconcileStorageObjects_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWorkspaceVolumeStates provides a mock function for the type Manager
func (_mock *Manager) SyncWorkspaceVolumeStates(ctx context.Context) (maintenance.VolumeStateSyncReport, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncWorkspaceVolumeStates")
	}

	var r0 maintenance.VolumeStateSyncReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (maintenance.VolumeStateSyncReport, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) maintenance.VolumeStateSyncReport); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(maintenance.VolumeStateSyncReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_SyncWorkspaceVolumeStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWorkspaceVolumeStates'
type Manager_SyncWorkspaceVolumeStates_Call struct {
	*mock.Call
}

// SyncWorkspaceVolumeStates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Manager_Expecter) SyncWorkspaceVolumeStates(ctx interface{}) *Manager_SyncWorkspaceVolumeStates_Call {
	return &Manager_SyncWorkspaceVolumeStates_Call{Call: _e.mock.On("SyncWorkspaceVolumeStates", ctx)}
}

func (_c *Manager_SyncWorkspaceVolumeStates_Call) Run(run func(ctx context.Context)) *Manager_SyncWorkspaceVolumeStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_SyncWorkspaceVolumeStates_Call) Return(volumeStateSyncReport maintenance.VolumeStateSyncReport, err error) *Manager_SyncWorkspaceVolumeStates_Call {
	_c.Call.Return(volumeStateSyncReport, err)
	return _c
}

func (_c *Manager_SyncWorkspaceVolumeStates_Call) RunAndReturn(run func(ctx context.Context) (maintenance.VolumeStateSyncReport, error)) *Manager_SyncWorkspaceVolumeStates_Call {
	_c.Call.Return(run)
	return _c
}
