// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmaintenance

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewOperator creates a new instance of Operator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Operator {
	mock := &Operator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Operator is an autogenerated mock type for the Operator type
type Operator struct {
	mock.Mock
}

type Operator_Expecter struct {
	mock *mock.Mock
}

func (_m *Operator) EXPECT() *Operator_Expecter {
	return &Operator_Expecter{mock: &_m.Mock}
}

// PerformMaintenance provides a mock function for the type Operator
func (_mock *Operator) PerformMaintenance(ctx context.Context, timestamp time.Time) error {
	ret := _mock.Called(ctx, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for PerformMaintenance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, timestamp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Operator_PerformMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformMaintenance'
type Operator_PerformMaintenance_Call struct {
	*mock.Call
}

// PerformMaintenance is a helper method to define mock.On call
//   - ctx context.Context
//   - timestamp time.Time
func (_e *Operator_Expecter) PerformMaintenance(ctx interface{}, timestamp interface{}) *Operator_PerformMaintenance_Call {
	return &Operator_PerformMaintenance_Call{Call: _e.mock.On("PerformMaintenance", ctx, timestamp)}
}

func (_c *Operator_PerformMaintenance_Call) Run(run func(ctx context.Context, timestamp time.Time)) *Operator_PerformMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Operator_PerformMaintenance_Call) Return(err error) *Operator_PerformMaintenance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Operator_PerformMaintenance_Call) RunAndReturn(run func(ctx context.Context, timestamp time.Time) error) *Operator_PerformMaintenance_Call {
	_c.Call.Return(run)
	return _c
}
