// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmaintenance

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTrigger creates a new instance of Trigger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrigger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Trigger {
	mock := &Trigger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Trigger is an autogenerated mock type for the Trigger type
type Trigger struct {
	mock.Mock
}

type Trigger_Expecter struct {
	mock *mock.Mock
}

func (_m *Trigger) EXPECT() *Trigger_Expecter {
	return &Trigger_Expecter{mock: &_m.Mock}
}

// RequestMaintenance provides a mock function for the type Trigger
func (_mock *Trigger) RequestMaintenance(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RequestMaintenance")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Trigger_RequestMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestMaintenance'
type Trigger_RequestMaintenance_Call struct {
	*mock.Call
}

// RequestMaintenance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Trigger_Expecter) RequestMaintenance(ctx interface{}) *Trigger_RequestMaintenance_Call {
	return &Trigger_RequestMaintenance_Call{Call: _e.mock.On("RequestMaintenance", ctx)}
}

func (_c *Trigger_RequestMaintenance_Call) Run(run func(ctx context.Context)) *Trigger_RequestMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trigger_RequestMaintenance_Call) Return(s string, err error) *Trigger_RequestMaintenance_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Trigger_RequestMaintenance_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *Trigger_RequestMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// StartTimer provides a mock function for the type Trigger
func (_mock *Trigger) StartTimer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartTimer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Trigger_StartTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTimer'
type Trigger_StartTimer_Call struct {
	*mock.Call
}

// StartTimer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Trigger_Expecter) StartTimer(ctx interface{}) *Trigger_StartTimer_Call {
	return &Trigger_StartTimer_Call{Call: _e.mock.On("StartTimer", ctx)}
}

func (_c *Trigger_StartTimer_Call) Run(run func(ctx context.Context)) *Trigger_StartTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trigger_StartTimer_Call) Return(err error) *Trigger_StartTimer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Trigger_StartTimer_Call) RunAndReturn(run func(ctx context.Context) error) *Trigger_StartTimer_Call {
	_c.Call.Return(run)
	return _c
}

// StopTimer provides a mock function for the type Trigger
func (_mock *Trigger) StopTimer(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StopTimer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Trigger_StopTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopTimer'
type Trigger_StopTimer_Call struct {
	*mock.Call
}

// StopTimer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Trigger_Expecter) StopTimer(ctx interface{}) *Trigger_StopTimer_Call {
	return &Trigger_StopTimer_Call{Call: _e.mock.On("StopTimer", ctx)}
}

func (_c *Trigger_StopTimer_Call) Run(run func(ctx context.Context)) *Trigger_StopTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Trigger_StopTimer_Call) Return(err error) *Trigger_StopTimer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Trigger_StopTimer_Call) RunAndReturn(run func(ctx context.Context) error) *Trigger_StopTimer_Call {
	_c.Call.Return(run)
	return _c
}
